### ISSUE TITLE
連結無法使用

### ISSUE THREAD

**Issue by azdkj532** [uranusjr/django-tutorial-for-programmers#13]
README.md中的超連結 http://ithelp.ithome.com.tw/ironman7/app/profile/20091495/dev 無法使用

**Comment by uranusjr** [comment]
去找 ITHome 抱怨。

**Comment by noracami** [comment]
http://ithelp.ithome.com.tw/ironman7/app/#/profile/20091495/dev `app/#/`
不曉得 ITHome 為什麼麼這麼設計就是了 :sweat:
