### ISSUE TITLE
In the tutorial 4, when executing python manage.py migrate, the error msg "The SECRET_KEY setting must not be empty" is thrown out.

### ISSUE THREAD

**Issue by Manuel4131** [uranusjr/django-tutorial-for-programmers#18]
When users need to change the setting to **local** in the **settings** directory, users also need to 
change the **manage.py** file. The default one is:
 * os.environ.setdefault("DJANGO_SETTINGS_MODULE", "PROJECT_NAME.settings")

 But real path is 
 * os.environ.setdefault("DJANGO_SETTINGS_MODULE", "PROJECT_NAME.settings.local")

Otherwise, the settings won't be found.

**Comment by noracami** [comment]
[FYI](https://github.com/uranusjr/django-tutorial-for-programmers/blame/master/04-run-your-project.md#L86-L109)

**Comment by uranusjr** [comment]
The `settings.py` file is not moved until chapter 4, in which the environ setup is also addressed (see above comment). Closing as invalid.
