### ISSUE TITLE
17-template-tags-and-ajax 缺一行

### ISSUE THREAD

**Issue by AndyHuang1991** [uranusjr/django-tutorial-for-programmers#32]
在base/static/base/js/base.js講到複製django doc的程式碼，可是好像漏了一行
fun getCookie宣告完沒有宣告變數
var csrftoken = getCookie('csrftoken');

加上這行Ajax才會作用@@"

**Comment by uranusjr** [comment]
我沒用到 `csrftoken` 這個變數啊，只有下面這行有用到 `getCookie`

https://github.com/uranusjr/django-tutorial-for-programmers/blob/410fd2dc17cd43aeac5837aa2a4743f099ebf8ad/lunch/lunch/base/static/base/js/base.js#L24

**Comment by AndyHuang1991** [comment]
後來刪除真的沒事，抱歉是我自己在js檔裡面漏東西@@"
可能是後來檢查完補上這行的同時也把有錯誤的小地方修改掉所以好了讓我以為是少了這行所以無法刪除

自己的疏失 抱歉QQ"
